apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Pour un test local, 1 replica suffit (et ça démarre plus vite)
patches:
  - target:
      kind: Deployment
      name: player-data-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

# Mets ici l'image de ta GHCR (tu peux la laisser sur latest pour le test)
images:
  - name: ghcr.io/isoardimarius/player-data-service
    newName: ghcr.io/isoardimarius/player-data-service
    newTag: latest