apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - network/ingress.yaml

patches:
  - path: patches/deployment-replicas.yaml
    target:
      kind: Deployment
      name: player-data-service

images:
  - name: ghcr.io/isoardimarius/player-data-service
    newName: ghcr.io/isoardimarius/player-data-service
    digest: sha256:0787941ee5396de0e77d20e7d39f4dff4effc34197e6e16126c11b2b2ec8bd89
