apiVersion: v1
kind: ServiceAccount
metadata:
  name: player-data-service
  labels:
    app.kubernetes.io/name: player-data-service
    app.kubernetes.io/part-of: opus-major-assignment
    app.kubernetes.io/component: api
