apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: player-data-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: opus-major
  source:
    repoURL: https://github.com/IsoardiMarius/opus-major-assignment.git
    targetRevision: main
    path: deploy/workloads/player-data-service/overlays/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: opus-major
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
