apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: player-data-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/IsoardiMarius/opus-major-assignment.git
    targetRevision: main
    path: deploy/kustomize/overlays/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: opus-major
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true