apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - core/namespace.yaml
  - core/serviceaccount.yaml
  - core/deployment.yaml
  - core/service.yaml
  - core/pdb.yaml
  - security/networkpolicy.yaml
  - observability/prometheus-rules-configmap.yaml
  - observability/grafana-dashboard-configmap.yaml
  - observability/servicemonitor.yaml
