apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: patches/patch-deployment-replicas.yaml
    target:
      kind: Deployment
      name: player-data-service

images:
  - name: ghcr.io/isoardimarius/player-data-service
    newName: ghcr.io/isoardimarius/player-data-service
    digest: sha256:84bfd6566d2b8acbd38098f7353686e028468d918e85780f945bfb7242bec7e2
